apiVersion: v1
kind: ConfigMap
metadata:
  name: devc-cfgmap
  namespace: {{ .Release.Namespace}}
data:
  devc.conf: |
    {
      "deploy":{
        "plugins":{
          "controller":{
            "namespace":{{ .Release.Namespace | quote}},
            "workspace": {{ .Values.workspace | quote}},
            "domain":{{ .Values.domain | quote}},
            "ingress_annotations":{
              "cert-manager.io/issuer":{{ .Values.issuer | quote}},
              "cert-manager.io/issuer-group":{{ .Values.issuer_group | quote}},
              "cert-manager.io/issuer-kind":{{ .Values.issuer_kind | quote}}
            }
          }
        }
      }
    }
