apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devc-pvc
  labels: { app: devc-cli }
  namespace: {{ .Release.Namespace}}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
