apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devc-bind
  namespace: {{ .Release.Namespace}}
subjects:
- kind: ServiceAccount
  name: devc-sa
  namespace: {{ .Release.Namespace}}
roleRef:
  kind: Role
  name: devc-pod
  apiGroup: rbac.authorization.k8s.io
