apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devc-pod
  namespace: {{ .Release.Namespace}}
rules:
- apiGroups: [""]
  resources: ["services", "persistentvolumeclaims","configmaps"]
  verbs: ["get", "list", "create", "delete", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "delete", "watch"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["gateways", "tcproutes"]
  verbs: ["get", "list", "create", "delete", "watch"]
