on:
  workflow_dispatch:
jobs:
  build:
    runs-on: 
      - ech00s-runner
    steps:
      - name: checkout
        uses: actions/checkout@v6
      
      - name: login
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build-images
        run: |
          TAG="bookworm"
          TARGETARCH="amd64"
          KUBECTL_VERSION="v1.35.6"

          LANGUAGES=(
            "cpp"
            "python"
            "go"
            "rust"
            "typescript-node"
            "java"
          )

          for LANGUAGE in "${LANGUAGES[@]}"; do
            IMAGE="ech00s/dev-container:${LANGUAGE}"

            echo "Building ${IMAGE}"

            docker build \
              -f dev-container-images/Dockerfile.template \
              --build-arg LANGUAGE="${LANGUAGE}" \
              --build-arg TAG="${TAG}" \
              --build-arg TARGETARCH="${TARGETARCH}" \
              --build-arg KUBECTL_VERSION="${KUBECTL_VERSION}" \
              -t "${IMAGE}" \
              images

          done
      
      - name: push-images
        run: 
          LANGUAGES=(
            "cpp"
            "python"
            "go"
            "rust"
            "typescript-node"
            "java"
          )
          
          for LANGUAGE in "${LANGUAGES[@]}"; do
            IMAGE="ech00s/dev-container:${LANGUAGE}"

            echo "Pushing ${IMAGE}"
            
            docker push $IMAGE

          done
